Repository AIFist/ChessAI, pull requests merged in 2023-08, with the labels that each got.

#15 Dragger is completer and clalc methosd is done
  Chess_Board/src/board.py
Labels: enhancement

#16 EHN: moving pieces are aded
  Chess_Board/src/board.py
  Chess_Board/src/main.py
  Chess_Board/src/move.py
  Chess_Board/src/piece.py
  Chess_Board/src/square.py
Labels: enhancement

#22 EHN : Addinf pawn promotion
  Chess_Board/src/board.py
  Chess_Board/src/game.py
  Chess_Board/src/main.py
Labels: enhancement

#25 ENH: in_check method is added
  Chess_Board/src/board.py
Labels: enhancement

#29 ENH: en_passant is added
  Chess_Board/src/board.py
  Chess_Board/src/config.py
  Chess_Board/src/main.py
  Chess_Board/src/piece.py
Labels: enhancement

#31 Youtube totail is done
  Chess_Board/src/board.py
Labels: enhancement

#34 Path issue resolve
  Chess_Board/src/piece.py
Labels: bug

#36 DOC: I write about set_true_EN_PASSANT
  Chess_Board/src/board.py
Labels: documentation

#40 Knight bug
  Chess_Board/src/board.py
  Chess_Board/src/game.py
Labels: bug
